CREATE TABLE TBD_ENDERECO (
ID_ENDERECO INT PRIMARY KEY IDENTITY(1,1) ,
RUA VARCHAR(200) NOT NULL,
CEP INT NOT NULL,
COMPLEMENTO VARCHAR(100) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
REFERENCIA VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
ESTADO VARCHAR(2) NOT NULL,
PAIS VARCHAR(100) NOT NULL
);

CREATE TABLE TBD_USUARIO (
ID_USUARIO INT PRIMARY KEY IDENTITY (1,1),
NOME_USUARIO VARCHAR(120) NOT NULL,
EMAIL_USUARIO VARCHAR(200) NOT NULL,
CPF_CNPJ VARCHAR(20) NOT NULL,
RG VARCHAR NOT NULL,
TELEFONE_USUARIO INT NOT NULL,
SENHA VARCHAR(16) NOT NULL,
PRESTADOR BIT NOT NULL,
SEXO CHAR(2) NOT NULL,
ESTADO_CIVIL VARCHAR(10) NOT NULL,
ID_ENDERECO INT FOREIGN KEY REFERENCES TBD_ENDERECO (ID_ENDERECO)
);

CREATE TABLE TBI_IMAGEM_USUARIO (
    IMAGEM_ID INT PRIMARY KEY IDENTITY (1,1),
    IMAGEM_URL VARCHAR(200) NOT NULL,
    ID_USUARIO INT FOREIGN KEY REFERENCES TBD_USUARIO(ID_USUARIO)
);

CREATE TABLE TBD_SERVICO (
    ID_SERVICO INT PRIMARY KEY IDENTITY (1,1),
    NOME_SERVICO VARCHAR(100) NOT NULL,
    DESCRICAO_SERVICO VARCHAR(5000) NOT NULL,
    TEMPO_EXECUCAO DATETIME NOT NULL,
    PRECO_SERVICO DECIMAL,
    LOCALIZACAO_FIXA BIT,
    ID_ENDERECO INT FOREIGN KEY REFERENCES TBD_ENDERECO (ID_ENDERECO),
    ID_USUARIO_PRESTADOR INT FOREIGN KEY REFERENCES TBD_USUARIO (ID_USUARIO)
);

CREATE TABLE TBD_DEMANDA (
    ID_DEMANDA INT PRIMARY KEY IDENTITY (1,1),
    NOME_DEMANDA VARCHAR(180),
    DESCRICAO_DEMANDA VARCHAR(5000) NOT NULL,
    VALOR_PREVISTO DECIMAL,
    ID_ENDERECO INT FOREIGN KEY REFERENCES TBD_ENDERECO NULL (ID_ENDERECO),
    ID_USUARIO_CONSUMIDOR INT FOREIGN KEY REFERENCES TBD_USUARIO (ID_USUARIO)
);

CREATE TABLE TBI_IMAGEM_SERVICO (
    ID_IMAGENS INT PRIMARY KEY IDENTITY (1,1),
    IMAGEM_URL VARCHAR(200)NOT NULL,
    ID_USUARIO INT FOREIGN KEY REFERENCES TBD_USUARIO (ID_USUARIO),
    ID_SERVICO INT FOREIGN KEY REFERENCES TBD_SERVICO (ID_SERVICO)
);


CREATE TABLE TBD_COMENTARIO (
    ID_COMENTARIO INT PRIMARY KEY IDENTITY (1,1),
    DE_COMENTARIO VARCHAR(1000) NOT NULL,
    DATA_COMENTARIO DATETIME NOT NULL,
    ID_SERVICO INT FOREIGN KEY REFERENCES TBD_SERVICO (ID_SERVICO),
    ID_USUARIO INT FOREIGN KEY REFERENCES TBD_USUARIO (ID_USUARIO)
);

CREATE TABLE TBI_CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY IDENTITY (1,1),
    NOME_CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE TBD_CONTRATO (
    ID_CONTRATO INT PRIMARY KEY IDENTITY (1,1),
    VALOR_FINAL DECIMAL,
    PAGO BIT NOT NULL,
    APROVADO_CONSUMIDOR BIT NOT NULL,
    APROVADO_PRESTADOR BIT NOT NULL,
    ID_USUARIO_PRESTADOR INT FOREIGN KEY REFERENCES USUARIO (ID_USUARIO),
    ID_SERVICO INT FOREIGN KEY REFERENCES TBD_SERVICO (ID_SERVICO),
    ID_DEMANDA INT FOREIGN KEY REFERENCES TBD_DEMANDA (ID_DEMANDA),
    ID_USUARIO_CONSUMIDOR INT FOREIGN KEY REFERENCES TBD_USUARIO (ID_USUARIO),
    ID_ENDERECO INT FOREIGN KEY REFERENCES TBD_ENDERECO (ID_ENDERECO)
);

CREATE TABLE TBD_DATAS_SERVICO_AGENDADO(
    ID_USUARIO_PRESTADOR INT FOREIGN KEY REFERENCES TBD_USUARIO (ID_USUARIO),
    ID_USUARIO_CONSUMIDOR INT FOREIGN KEY REFERENCES TBD_USUARIO (ID_USUARIO),
    ID_SERVICO INT FOREIGN KEY REFERENCES TBD_SERVICO (ID_SERVICO),
    ID_CONTRATO INT FOREIGN KEY REFERENCES TBD_CONTRATO (ID_CONTRATO),
    ID_DEMANDA INT FOREIGN KEY REFERENCES TBD_DEMANDA (ID_DEMANDA),
    DT_AGENDAMENTO DATETIME NOT NULL,
    TIPO_RESERVA CHAR(1)    
)

SELECT * FROM ENDERECO
SELECT * FROM USUARIO
SELECT * FROM  IMAGEM_USUARIO 
SELECT * FROM SERVICO
SELECT * FROM IMAGEM_SERVICO
SELECT * FROM COMENTARIO
SELECT * FROM CATEGORIA
SELECT * FROM CONTRATO
